import React, { Suspense, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, Float, OrbitControls } from '@react-three/drei';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Box, Cpu, Github, Mail, Menu, Play, X } from 'lucide-react';
import './styles.css';

type Project={title:string; category:string; type:string; description:string; tags:string[]; featured?:boolean};
const projects:Project[]=[
 {title:'Glas 1700 TS — Automotive Visualization',category:'3D',type:'Personal Project',description:'A reference-driven automotive modeling and visualization study focused on proportions, surfaces, materials and cinematic presentation.',tags:['Blender','Automotive','Rendering'],featured:true},
 {title:'PREPEAK Data-Center Visualization',category:'3D',type:'Freelance / Visualization Work',description:'Industrial visualization work exploring a complex technical environment through animation and presentation-focused 3D.',tags:['Blender','Animation','Industrial']},
 {title:'Line Following Robot',category:'Robotics',type:'Academic Project',description:'An embedded robotics prototype combining sensors, control logic and motor actuation.',tags:['Arduino','C','Sensors']},
 {title:'Maze Solving Robot',category:'Robotics',type:'Academic Project',description:'A mobile robotics experiment focused on navigation logic, sensing and autonomous decision making.',tags:['Embedded','Control','Robotics']},
 {title:'ESP32 Embedded Experiments',category:'Engineering',type:'Experiment',description:'Hands-on microcontroller experiments connecting firmware, sensors and physical systems.',tags:['ESP32','C++','IoT']},
 {title:'MATLAB Signal Processing Lab',category:'Engineering',type:'Academic Project',description:'Explorations in signal processing, analysis and visualization using MATLAB.',tags:['MATLAB','Signals','Engineering']},
 {title:'3D Product Visualization Lab',category:'3D',type:'Personal Project',description:'A product-focused study of hard-surface modeling, materials, lighting and controlled studio renders.',tags:['Blender','Product','Materials']},
 {title:'Hard Surface Modeling Studies',category:'3D',type:'Ongoing Project',description:'A growing collection of mechanical modeling exercises focused on precision and believable manufactured forms.',tags:['Blender','Hard Surface']},
 {title:'Procedural Mechanical Systems',category:'3D',type:'Experiment',description:'Procedural experiments investigating repeatable mechanical forms and motion.',tags:['Geometry','Procedural','Blender']},
 {title:'Interactive WebGL Laboratory',category:'Software',type:'Personal Project',description:'Experiments combining React, Three.js and interactive visual systems for the browser.',tags:['React','Three.js','WebGL']},
 {title:'Unity 3D Gameplay Prototype',category:'Games',type:'Prototype',description:'A gameplay sandbox exploring real-time movement, physics and interactive environments.',tags:['Unity','C#','3D']},
 {title:'Unity Physics Experiments',category:'Games',type:'Experiment',description:'Small physics-driven experiments used to understand real-time simulation and game interaction.',tags:['Unity','Physics','C#']},
 {title:'Android Utility Concepts',category:'Android',type:'Personal Project',description:'Android development experiments focused on practical utilities and interface design.',tags:['Android','Java','UI']},
 {title:'Python Automation Toolkit',category:'Software',type:'Personal Project',description:'Utility scripts and automation experiments for reducing repetitive technical workflows.',tags:['Python','Automation']},
 {title:'AI-Assisted Creative Workflow',category:'AI',type:'AI-Assisted Experiment',description:'Experiments combining generative AI with research, ideation, coding and creative production.',tags:['AI','Prompt Engineering','Automation']},
 {title:'AI + 3D Reference Pipeline',category:'AI',type:'AI-Assisted Experiment',description:'A workflow study moving from structured visual references toward 3D generation and cleanup.',tags:['AI','3D','Workflow']},
 {title:'Engineering Visualization System',category:'Engineering',type:'Concept',description:'A concept for explaining technical mechanisms through interactive visual storytelling.',tags:['Engineering','Visualization','WebGL']},
 {title:'Robotic Mechanism Study',category:'Robotics',type:'Ongoing Project',description:'Mechanical and kinematic exploration inspired by robotic mechanisms and mechatronic systems.',tags:['Robotics','Mechatronics','CAD']},
 {title:'Creative Coding Experiments',category:'Software',type:'Open-Source Experiment',description:'Small browser-based experiments exploring motion, interaction, shaders and generative systems.',tags:['TypeScript','Canvas','Web']},
 {title:'Interactive Engineering Playground',category:'Engineering',type:'Concept',description:'A planned interactive laboratory for communicating engineering ideas through simulation and visual interaction.',tags:['Simulation','Interaction','Engineering']}
];

function Core(){const ref=useRef<THREE.Group>(null!);useFrame((s)=>{if(ref.current){ref.current.rotation.y=s.clock.elapsedTime*.18;ref.current.rotation.x=Math.sin(s.clock.elapsedTime*.35)*.08}});return <group ref={ref}><Float speed={1.2} rotationIntensity={.25} floatIntensity={.45}><mesh><icosahedronGeometry args={[1.65,2]}/><meshStandardMaterial color="#a9afb3" metalness={.78} roughness={.2} wireframe/></mesh><mesh scale={.74}><icosahedronGeometry args={[1.65,1]}/><meshStandardMaterial color="#181b1d" metalness={.65} roughness={.24}/></mesh><mesh rotation={[Math.PI/2,0,0]} scale={1.85}><torusGeometry args={[1.45,.025,12,96]}/><meshStandardMaterial color="#c7ccd0" metalness={.9} roughness={.18}/></mesh></Float></group>}
function Hero3D(){return <div className="hero-canvas" aria-hidden="true"><Canvas dpr={[1,1.5]} camera={{position:[0,0,5.7],fov:42}} gl={{antialias:true,powerPreference:'high-performance'}}><ambientLight intensity={.35}/><directionalLight position={[3,4,5]} intensity={4}/><pointLight position={[-3,-2,2]} intensity={2}/><Suspense fallback={null}><Core/><Environment preset="studio"/></Suspense><OrbitControls enableZoom={false} enablePan={false} autoRotate={false}/></Canvas></div>}
function App(){const [filter,setFilter]=React.useState('ALL');const [menu,setMenu]=React.useState(false);const shown=filter==='ALL'?projects:projects.filter(p=>p.category.toUpperCase()===filter);return <div className="site">
 <header><a className="brand" href="#top"><span>MAH</span><small>CREATIVE TECHNOLOGY</small></a><nav className={menu?'open':''}>{['About','Projects','3D Lab','Engineering','Playground','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase().replace(' ','-')} onClick={()=>setMenu(false)}>{x}</a>)}<a className="nav-contact" href="mailto:hamza207205@gmail.com">Start a project <ArrowUpRight size={15}/></a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
 <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> DIGITAL WORKSHOP / 2026</p><h1>Building at the<br/><em>intersection</em> of<br/>3D, software &amp; engineering.</h1><p className="lede">I'm Muhammad Ameer Hamza — a creative technologist exploring 3D art, interactive software, robotics, mechatronics and AI-assisted workflows.</p><div className="hero-actions"><a className="button primary" href="#projects">Explore work <ArrowDown size={16}/></a><a className="button" href="mailto:hamza207205@gmail.com">Get in touch <Mail size={16}/></a></div></div><Hero3D/><div className="hero-meta"><span>01 / 04</span><span>Interactive system</span></div></section>
 <section className="manifesto" id="about"><div className="section-index">01 — IDENTITY</div><div><p className="statement">Not just a portfolio.<br/><strong>A working laboratory.</strong></p><p className="body-copy">I build visual and technical experiments where design meets engineering. From Blender scenes and automotive visualization to embedded systems, software and interactive 3D — the common thread is curiosity made tangible.</p></div></section>
 <section className="work" id="projects"><div className="section-head"><div><div className="section-index">02 — SELECTED WORK</div><h2>Proof of <em>practice.</em></h2></div><span className="count">{projects.length.toString().padStart(2,'0')} PROJECTS</span></div><div className="filters">{['ALL','3D','GAMES','SOFTWARE','ANDROID','ROBOTICS','ENGINEERING','AI'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="project-grid">{shown.map((p,i)=><motion.article layout key={p.title} className={'project '+(p.featured?'featured':'')}><div className="project-visual"><span>{String(i+1).padStart(2,'0')}</span><div className="visual-mark">{p.category==='3D'?<Box/>:p.category==='Robotics'?<Cpu/>:<Play/>}</div><small>{p.type}</small></div><div className="project-info"><div><p className="category">{p.category}</p><h3>{p.title}</h3></div><ArrowUpRight size={19}/><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></motion.article>)}</div></section>
 <section className="capabilities" id="3d-lab"><div className="section-index">03 — CAPABILITIES</div><div className="cap-grid"><div><h2>3D<br/><em>Visuals.</em></h2><p>Modeling, materials, lighting, animation, automotive and product visualization with Blender.</p></div><div><h2>Code<br/><em>Systems.</em></h2><p>React, TypeScript, Python, Android, Unity and interactive browser experiences.</p></div><div><h2>Engineering<br/><em>Mindset.</em></h2><p>Mechatronics, robotics, embedded systems, sensors, control and technical visualization.</p></div></div></section>
 <section className="playground" id="playground"><div className="section-index">04 — PLAYGROUND</div><div className="play-card"><div><p className="eyebrow">EXPERIMENTAL SPACE</p><h2>Where ideas get<br/><em>stress-tested.</em></h2></div><p>Procedural geometry, shaders, physics, robotic mechanisms and creative coding. This space will grow as the experiments do.</p><a className="button primary" href="#contact">Enter the lab <ArrowUpRight size={16}/></a></div></section>
 <section className="contact" id="contact"><div className="section-index">05 — CONTACT</div><h2>Have a system<br/>worth <em>building?</em></h2><p>For freelance 3D, visualization, software, interactive or engineering projects.</p><div className="contact-actions"><a className="button primary" href="mailto:hamza207205@gmail.com?subject=Project%20Inquiry">Email me <Mail size={16}/></a><a className="button" href="https://wa.me/923298753659?text=Hello%20Muhammad%2C%20I%27d%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={16}/></a></div></section></main>
 <footer><span>© 2026 Muhammad Ameer Hamza</span><span>3D / SOFTWARE / ENGINEERING / AI</span><a href="mailto:hamza207205@gmail.com">hamza207205@gmail.com</a></footer></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
